name: glaucoma-fov-env
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10.*
  - pip
  - pytorch=2.1.2=py3.10_cuda11.8*
  - torchvision=0.16.2=py310_cu118*
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - numpy=1.26.4
  - matplotlib=3.7.1
  - scipy=1.10.1
  - pyyaml=6.0.1
  - pandas=1.5.3
  - seaborn=0.12.2
  - psutil
  - tqdm=4.64.0
  - ipython
  - albumentations>=1.3.0
  - pip:
      - thop==0.1.1.post2209072238
      - tensorboard==2.13.0
      - requests>=2.23.0
      - Pillow==9.4.0
      - gitpython
      - pycocotools>=2.0