name: glaucoma-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - pandas
  - tqdm
  - scikit-learn
  - pysaliency
  - scikit-image
  - pip:
    - opencv-contrib-python