name: glaucoma-fov-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pytorch-cuda=11.8
  - numpy=1.26.4
  - opencv=4.9.0.80         # Avoid OpenCV 4.10+ (some I/O changes)
  - matplotlib=3.7.1
  - scipy=1.10.1         # Safe mid-range version
  - pyyaml=6.0.1
  - pandas=1.5.3
  - seaborn=0.12.2
  - psutil
  - tqdm
  - ipython
  - pip:
      - thop==0.1.1.post2209072238
      - tensorboard==2.13.0
      - requests>=2.23.0
      - Pillow==9.4.0
      - gitpython
      - albumentations>=1.0.3
      - pycocotools>=2.0